### ISSUE TITLE
使用pytorch提示错误cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by CLAYGUAN** [GuanceCloud/dataflux-func#2]
环境信息：Apple M1 Max  
                  dataflux-func 2.6.39
                  torch 2.0.1
执行脚本提示：
    import torch
ImportError: /data/resources/extra-python-packages/torch/lib/../../torch.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block

**Comment by pastgift** [comment]
这个问题与 DataFlux Func 无关

你可以参考下面的解决方案
https://stackoverflow.com/questions/61065541/importerror-usr-lib-aarch64-linux-gnu-libgomp-so-1-cannot-allocate-memory-in

> 注意：PIP 工具安装的包不在默认路径下，libgomp.so 路径应更换为实际报错提示的路径

**Comment by pastgift** [comment]
太久没有回复，关闭处理
